forge 'https://forgeapi.puppetlabs.com'

mod 'puppet-collectd', '5.3.0'
mod 'puppet/archive', '1.3.0'
mod 'puppetlabs/java_ks', '1.5.0'
mod 'puppetlabs/stdlib', '4.21.0'
mod 'puppet-healthcheck', '0.4.0'
mod 'puppet-logrotate', '3.2.1'
mod 'puppet-yum', '0.10.0'
mod 'puppetlabs-concat', '2.2.1'
mod 'shinesolutions/aem_orchestrator', '1.2.0'
mod 'shinesolutions/aem_resources', '2.2.5'
mod 'shinesolutions/aem_curator', '0.9.29'
mod 'shinesolutions/simianarmy', '1.1.1'
